
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3447072
     no. of nonzeroes in the factor l        =         6551237
     ratio of nonzeroes in factor (min/max)  =          0.9547
     number of super nodes                   =             607
     maximum order of a front matrix         =            2631
     maximum size of a front matrix          =         3462396
     maximum size of a front trapezoid       =         1796505
     no. of floating point ops for factor    =      7.2566D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9212
     ratio of allocated memory (max/min)     =          1.2288
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.011115
     time (cpu & wall) for ordering          =        0.078125        0.085797
     time (cpu & wall) for other matrix prep =        0.015625        0.010568
     time (cpu & wall) for value input       =        0.015625        0.033715
     time (cpu & wall) for matrix distrib.   =        0.062500        0.105672
     time (cpu & wall) for numeric factor    =        0.125000        0.192548
     computational rate (gflops) for factor  =       58.052538       37.687017

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         59061.        0. MB
                95-   1        131072.        1. MB        101414.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160475.        1. MB


  Solver Memory allocated on core    0       =      124.353 MB
  Solver Memory allocated on core    1       =      152.805 MB
  Total Solver Memory allocated by all cores =      277.157 MB





  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =          773217
     no. of nonzeroes in the factor l        =         3354485
     ratio of nonzeroes in factor (min/max)  =          0.5748
     number of super nodes                   =             628
     maximum order of a front matrix         =             537
     maximum size of a front matrix          =          144453
     maximum size of a front trapezoid       =          111042
     no. of floating point ops for factor    =      7.6582D+08
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.7227
     ratio of allocated memory (max/min)     =          1.5462
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             189
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.003007
     time (cpu & wall) for ordering          =        0.015625        0.029077
     time (cpu & wall) for other matrix prep =        0.000000        0.005050
     time (cpu & wall) for value input       =        0.000000        0.011429
     time (cpu & wall) for matrix distrib.   =        0.015625        0.020115
     time (cpu & wall) for numeric factor    =        0.015625        0.036230
     computational rate (gflops) for factor  =       49.012179       21.137310

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         50540.        0. MB
                95-   1        131072.        1. MB        105586.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        156126.        1. MB


  Solver Memory allocated on core    0       =       37.259 MB
  Solver Memory allocated on core    1       =       57.609 MB
  Total Solver Memory allocated by all cores =       94.867 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3447072
     no. of nonzeroes in the factor l        =         6551237
     ratio of nonzeroes in factor (min/max)  =          0.9547
     number of super nodes                   =             607
     maximum order of a front matrix         =            2631
     maximum size of a front matrix          =         3462396
     maximum size of a front trapezoid       =         1796505
     no. of floating point ops for factor    =      7.2566D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9212
     ratio of allocated memory (max/min)     =          1.2288
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.010968
     time (cpu & wall) for ordering          =        0.031250        0.082452
     time (cpu & wall) for other matrix prep =        0.015625        0.009820
     time (cpu & wall) for value input       =        0.015625        0.035061
     time (cpu & wall) for matrix distrib.   =        0.078125        0.100287
     time (cpu & wall) for numeric factor    =        0.203125        0.199598
     computational rate (gflops) for factor  =       35.724639       36.355857

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         59061.        0. MB
                95-   1        131072.        1. MB        101414.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160475.        1. MB


  Solver Memory allocated on core    0       =      124.353 MB
  Solver Memory allocated on core    1       =      152.805 MB
  Total Solver Memory allocated by all cores =      277.157 MB





  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =          781137
     no. of nonzeroes in the factor l        =         3403724
     ratio of nonzeroes in factor (min/max)  =          0.4996
     number of super nodes                   =             628
     maximum order of a front matrix         =             537
     maximum size of a front matrix          =          144453
     maximum size of a front trapezoid       =          111042
     no. of floating point ops for factor    =      7.8516D+08
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.2884
     ratio of allocated memory (max/min)     =          1.3948
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.003320
     time (cpu & wall) for ordering          =        0.015625        0.027765
     time (cpu & wall) for other matrix prep =        0.000000        0.004828
     time (cpu & wall) for value input       =        0.000000        0.011440
     time (cpu & wall) for matrix distrib.   =        0.031250        0.024027

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         75754.        1. MB
                95-   1         98304.        1. MB         80806.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        156560.        1. MB


  Solver Memory allocated on core    0       =       55.537 MB
  Solver Memory allocated on core    1       =       39.817 MB
  Total Solver Memory allocated by all cores =       95.354 MB





  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3511512
     no. of nonzeroes in the factor l        =         6820759
     ratio of nonzeroes in factor (min/max)  =          0.7932
     number of super nodes                   =             599
     maximum order of a front matrix         =            2601
     maximum size of a front matrix          =         3383901
     maximum size of a front trapezoid       =         3264096
     no. of floating point ops for factor    =      8.1104D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9999
     ratio of allocated memory (max/min)     =          1.0954
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               7
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.011542
     time (cpu & wall) for ordering          =        0.078125        0.092409
     time (cpu & wall) for other matrix prep =        0.000000        0.009611
     time (cpu & wall) for value input       =        0.015625        0.061000
     time (cpu & wall) for matrix distrib.   =        0.046875        0.093541
     time (cpu & wall) for numeric factor    =        0.187500        0.212437
     computational rate (gflops) for factor  =       43.255508       38.177980
     time (cpu & wall) for numeric solve     =        0.031250        0.006588
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        110750.        1. MB
                95-   1         65536.        0. MB         48638.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        159388.        1. MB


  Solver Memory allocated on core    0       =      140.812 MB
  Solver Memory allocated on core    1       =      154.240 MB
  Total Solver Memory allocated by all cores =      295.052 MB





  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3511512
     no. of nonzeroes in the factor l        =         6893885
     ratio of nonzeroes in factor (min/max)  =          0.7293
     number of super nodes                   =             609
     maximum order of a front matrix         =            2682
     maximum size of a front matrix          =         3597903
     maximum size of a front trapezoid       =         2112165
     no. of floating point ops for factor    =      8.1712D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9658
     ratio of allocated memory (max/min)     =          1.0715
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.012448
     time (cpu & wall) for ordering          =        0.078125        0.087622
     time (cpu & wall) for other matrix prep =        0.000000        0.009619
     time (cpu & wall) for value input       =        0.031250        0.059702
     time (cpu & wall) for matrix distrib.   =        0.046875        0.091419
     time (cpu & wall) for numeric factor    =        0.203125        0.227682
     computational rate (gflops) for factor  =       40.227413       35.888591

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107850.        1. MB
                95-   1         65536.        0. MB         53922.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        161772.        1. MB


  Solver Memory allocated on core    0       =      140.806 MB
  Solver Memory allocated on core    1       =      150.873 MB
  Total Solver Memory allocated by all cores =      291.679 MB





  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3511512
     no. of nonzeroes in the factor l        =         6893885
     ratio of nonzeroes in factor (min/max)  =          0.7293
     number of super nodes                   =             609
     maximum order of a front matrix         =            2682
     maximum size of a front matrix          =         3597903
     maximum size of a front trapezoid       =         2112165
     no. of floating point ops for factor    =      8.1712D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9658
     ratio of allocated memory (max/min)     =          1.0714
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.011404
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.061643
     time (cpu & wall) for matrix distrib.   =        0.093750        0.111429
     time (cpu & wall) for numeric factor    =        0.156250        0.222391
     computational rate (gflops) for factor  =       52.295637       36.742464

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107850.        1. MB
                95-   1         65536.        0. MB         53922.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        161772.        1. MB


  Solver Memory allocated on core    0       =      140.844 MB
  Solver Memory allocated on core    1       =      150.904 MB
  Total Solver Memory allocated by all cores =      291.749 MB





  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3511512
     no. of nonzeroes in the factor l        =         6893885
     ratio of nonzeroes in factor (min/max)  =          0.7293
     number of super nodes                   =             609
     maximum order of a front matrix         =            2682
     maximum size of a front matrix          =         3597903
     maximum size of a front trapezoid       =         2112165
     no. of floating point ops for factor    =      8.1712D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9658
     ratio of allocated memory (max/min)     =          1.0714
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.013471
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.067999
     time (cpu & wall) for matrix distrib.   =        0.062500        0.096116
     time (cpu & wall) for numeric factor    =        0.234375        0.261527
     computational rate (gflops) for factor  =       34.863758       31.244119

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107850.        1. MB
                95-   1         65536.        0. MB         53922.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        161772.        1. MB


  Solver Memory allocated on core    0       =      140.840 MB
  Solver Memory allocated on core    1       =      150.898 MB
  Total Solver Memory allocated by all cores =      291.738 MB





  Performance statistics for DSP solver: icalls =      9

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3511512
     no. of nonzeroes in the factor l        =         6893885
     ratio of nonzeroes in factor (min/max)  =          0.7293
     number of super nodes                   =             609
     maximum order of a front matrix         =            2682
     maximum size of a front matrix          =         3597903
     maximum size of a front trapezoid       =         2112165
     no. of floating point ops for factor    =      8.1712D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9658
     ratio of allocated memory (max/min)     =          1.0714
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.057175
     time (cpu & wall) for matrix distrib.   =        0.078125        0.091092
     time (cpu & wall) for numeric factor    =        0.171875        0.225149
     computational rate (gflops) for factor  =       47.541488       36.292429
     time (cpu & wall) for numeric solve     =        0.015625        0.007631
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107850.        1. MB
                95-   1         65536.        0. MB         53922.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        161772.        1. MB


  Solver Memory allocated on core    0       =      140.840 MB
  Solver Memory allocated on core    1       =      150.898 MB
  Total Solver Memory allocated by all cores =      291.738 MB





  Performance statistics for DSP solver: icalls =     10

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3511512
     no. of nonzeroes in the factor l        =         6893885
     ratio of nonzeroes in factor (min/max)  =          0.7293
     number of super nodes                   =             609
     maximum order of a front matrix         =            2682
     maximum size of a front matrix          =         3597903
     maximum size of a front trapezoid       =         2112165
     no. of floating point ops for factor    =      8.1712D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9658
     ratio of allocated memory (max/min)     =          1.0714
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.057032
     time (cpu & wall) for matrix distrib.   =        0.078125        0.089797
     time (cpu & wall) for numeric factor    =        0.234375        0.262539
     computational rate (gflops) for factor  =       34.863758       31.123779

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107850.        1. MB
                95-   1         65536.        0. MB         53922.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        161772.        1. MB


  Solver Memory allocated on core    0       =      140.840 MB
  Solver Memory allocated on core    1       =      150.898 MB
  Total Solver Memory allocated by all cores =      291.738 MB





  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3511512
     no. of nonzeroes in the factor l        =         6893885
     ratio of nonzeroes in factor (min/max)  =          0.7293
     number of super nodes                   =             609
     maximum order of a front matrix         =            2682
     maximum size of a front matrix          =         3597903
     maximum size of a front trapezoid       =         2112165
     no. of floating point ops for factor    =      8.1712D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9658
     ratio of allocated memory (max/min)     =          1.0714
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.057819
     time (cpu & wall) for matrix distrib.   =        0.046875        0.091110
     time (cpu & wall) for numeric factor    =        0.171875        0.212400
     computational rate (gflops) for factor  =       47.541488       38.470724

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107850.        1. MB
                95-   1         65536.        0. MB         53922.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        161772.        1. MB


  Solver Memory allocated on core    0       =      140.840 MB
  Solver Memory allocated on core    1       =      150.898 MB
  Total Solver Memory allocated by all cores =      291.738 MB





  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3511512
     no. of nonzeroes in the factor l        =         6893885
     ratio of nonzeroes in factor (min/max)  =          0.7293
     number of super nodes                   =             609
     maximum order of a front matrix         =            2682
     maximum size of a front matrix          =         3597903
     maximum size of a front trapezoid       =         2112165
     no. of floating point ops for factor    =      8.1712D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9658
     ratio of allocated memory (max/min)     =          1.0714
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.060807
     time (cpu & wall) for matrix distrib.   =        0.062500        0.108271
     time (cpu & wall) for numeric factor    =        0.203125        0.202992
     computational rate (gflops) for factor  =       40.227413       40.253711

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107850.        1. MB
                95-   1         65536.        0. MB         53922.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        161772.        1. MB


  Solver Memory allocated on core    0       =      140.840 MB
  Solver Memory allocated on core    1       =      150.898 MB
  Total Solver Memory allocated by all cores =      291.738 MB





  Performance statistics for DSP solver: icalls =     13

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3511512
     no. of nonzeroes in the factor l        =         6893885
     ratio of nonzeroes in factor (min/max)  =          0.7293
     number of super nodes                   =             609
     maximum order of a front matrix         =            2682
     maximum size of a front matrix          =         3597903
     maximum size of a front trapezoid       =         2112165
     no. of floating point ops for factor    =      8.1712D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9658
     ratio of allocated memory (max/min)     =          1.0714
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.011573
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.056899
     time (cpu & wall) for matrix distrib.   =        0.093750        0.095230
     time (cpu & wall) for numeric factor    =        0.171875        0.232928
     computational rate (gflops) for factor  =       47.541488       35.080355

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107850.        1. MB
                95-   1         65536.        0. MB         53922.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        161772.        1. MB


  Solver Memory allocated on core    0       =      140.842 MB
  Solver Memory allocated on core    1       =      150.901 MB
  Total Solver Memory allocated by all cores =      291.743 MB





  Performance statistics for DSP solver: icalls =     14

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3450870
     no. of nonzeroes in the factor l        =         7032384
     ratio of nonzeroes in factor (min/max)  =          0.8793
     number of super nodes                   =             603
     maximum order of a front matrix         =            2568
     maximum size of a front matrix          =         3298596
     maximum size of a front trapezoid       =         1980048
     no. of floating point ops for factor    =      8.2363D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9502
     ratio of allocated memory (max/min)     =          1.2618
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.013594
     time (cpu & wall) for ordering          =        0.062500        0.093198
     time (cpu & wall) for other matrix prep =        0.000000        0.011879
     time (cpu & wall) for value input       =        0.000000        0.059261
     time (cpu & wall) for matrix distrib.   =        0.046875        0.099329
     time (cpu & wall) for numeric factor    =        0.187500        0.231881
     computational rate (gflops) for factor  =       43.927167       35.519640

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         53849.        0. MB
                95-   1        131072.        1. MB        109263.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        163112.        1. MB


  Solver Memory allocated on core    0       =      127.903 MB
  Solver Memory allocated on core    1       =      161.390 MB
  Total Solver Memory allocated by all cores =      289.293 MB





  Performance statistics for DSP solver: icalls =     15

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3449790
     no. of nonzeroes in the factor l        =         6910873
     ratio of nonzeroes in factor (min/max)  =          0.7416
     number of super nodes                   =             603
     maximum order of a front matrix         =            2631
     maximum size of a front matrix          =         3462396
     maximum size of a front trapezoid       =         1980048
     no. of floating point ops for factor    =      8.1183D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9065
     ratio of allocated memory (max/min)     =          1.0466
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.011646
     time (cpu & wall) for ordering          =        0.078125        0.088044
     time (cpu & wall) for other matrix prep =        0.000000        0.009684
     time (cpu & wall) for value input       =        0.015625        0.062978
     time (cpu & wall) for matrix distrib.   =        0.078125        0.096837
     time (cpu & wall) for numeric factor    =        0.171875        0.229053
     computational rate (gflops) for factor  =       47.233766       35.442858
     time (cpu & wall) for numeric solve     =        0.015625        0.007812
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        104700.        1. MB
                95-   1         65536.        0. MB         57031.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        161731.        1. MB


  Solver Memory allocated on core    0       =      140.418 MB
  Solver Memory allocated on core    1       =      146.957 MB
  Total Solver Memory allocated by all cores =      287.375 MB





  Performance statistics for DSP solver: icalls =     16

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3449655
     no. of nonzeroes in the factor l        =         6843318
     ratio of nonzeroes in factor (min/max)  =          0.7272
     number of super nodes                   =             589
     maximum order of a front matrix         =            2580
     maximum size of a front matrix          =         3329490
     maximum size of a front trapezoid       =         1761501
     no. of floating point ops for factor    =      7.8480D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9895
     ratio of allocated memory (max/min)     =          1.0810
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.010583
     time (cpu & wall) for ordering          =        0.062500        0.090307
     time (cpu & wall) for other matrix prep =        0.000000        0.012162
     time (cpu & wall) for value input       =        0.046875        0.057509
     time (cpu & wall) for matrix distrib.   =        0.093750        0.092135
     time (cpu & wall) for numeric factor    =        0.171875        0.199087
     computational rate (gflops) for factor  =       45.660948       39.419809

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        112000.        1. MB
                95-   1         65536.        0. MB         48965.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160965.        1. MB


  Solver Memory allocated on core    0       =      138.241 MB
  Solver Memory allocated on core    1       =      149.443 MB
  Total Solver Memory allocated by all cores =      287.684 MB





  Performance statistics for DSP solver: icalls =     17

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3449655
     no. of nonzeroes in the factor l        =         6843318
     ratio of nonzeroes in factor (min/max)  =          0.7272
     number of super nodes                   =             589
     maximum order of a front matrix         =            2580
     maximum size of a front matrix          =         3329490
     maximum size of a front trapezoid       =         1761501
     no. of floating point ops for factor    =      7.8480D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9895
     ratio of allocated memory (max/min)     =          1.0809
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.012370
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.068822
     time (cpu & wall) for matrix distrib.   =        0.078125        0.099043
     time (cpu & wall) for numeric factor    =        0.156250        0.242871
     computational rate (gflops) for factor  =       50.227043       32.313296

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        112000.        1. MB
                95-   1         65536.        0. MB         48965.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160965.        1. MB


  Solver Memory allocated on core    0       =      138.278 MB
  Solver Memory allocated on core    1       =      149.472 MB
  Total Solver Memory allocated by all cores =      287.750 MB





  Performance statistics for DSP solver: icalls =     18

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3449655
     no. of nonzeroes in the factor l        =         6843318
     ratio of nonzeroes in factor (min/max)  =          0.7272
     number of super nodes                   =             589
     maximum order of a front matrix         =            2580
     maximum size of a front matrix          =         3329490
     maximum size of a front trapezoid       =         1761501
     no. of floating point ops for factor    =      7.8480D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9895
     ratio of allocated memory (max/min)     =          1.0810
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.010857
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.057274
     time (cpu & wall) for matrix distrib.   =        0.078125        0.094838
     time (cpu & wall) for numeric factor    =        0.218750        0.241393
     computational rate (gflops) for factor  =       35.876459       32.511184

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        112000.        1. MB
                95-   1         65536.        0. MB         48965.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160965.        1. MB


  Solver Memory allocated on core    0       =      138.280 MB
  Solver Memory allocated on core    1       =      149.475 MB
  Total Solver Memory allocated by all cores =      287.755 MB





  Performance statistics for DSP solver: icalls =     19

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3449655
     no. of nonzeroes in the factor l        =         6843318
     ratio of nonzeroes in factor (min/max)  =          0.7272
     number of super nodes                   =             589
     maximum order of a front matrix         =            2580
     maximum size of a front matrix          =         3329490
     maximum size of a front trapezoid       =         1761501
     no. of floating point ops for factor    =      7.8480D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9895
     ratio of allocated memory (max/min)     =          1.0810
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.010770
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.061723
     time (cpu & wall) for matrix distrib.   =        0.093750        0.100690
     time (cpu & wall) for numeric factor    =        0.203125        0.211395
     computational rate (gflops) for factor  =       38.636187       37.124698

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        112000.        1. MB
                95-   1         65536.        0. MB         48965.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160965.        1. MB


  Solver Memory allocated on core    0       =      138.278 MB
  Solver Memory allocated on core    1       =      149.474 MB
  Total Solver Memory allocated by all cores =      287.752 MB





  Performance statistics for DSP solver: icalls =     20

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3449655
     no. of nonzeroes in the factor l        =         6843318
     ratio of nonzeroes in factor (min/max)  =          0.7272
     number of super nodes                   =             589
     maximum order of a front matrix         =            2580
     maximum size of a front matrix          =         3329490
     maximum size of a front trapezoid       =         1761501
     no. of floating point ops for factor    =      7.8480D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9895
     ratio of allocated memory (max/min)     =          1.0810
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.010960
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.078125        0.059107
     time (cpu & wall) for matrix distrib.   =        0.078125        0.096404
     time (cpu & wall) for numeric factor    =        0.140625        0.209133
     computational rate (gflops) for factor  =       55.807826       37.526313
     time (cpu & wall) for numeric solve     =        0.015625        0.007905
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        112000.        1. MB
                95-   1         65536.        0. MB         48965.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160965.        1. MB


  Solver Memory allocated on core    0       =      138.280 MB
  Solver Memory allocated on core    1       =      149.475 MB
  Total Solver Memory allocated by all cores =      287.755 MB





  Performance statistics for DSP solver: icalls =     21

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3449655
     no. of nonzeroes in the factor l        =         6843318
     ratio of nonzeroes in factor (min/max)  =          0.7272
     number of super nodes                   =             589
     maximum order of a front matrix         =            2580
     maximum size of a front matrix          =         3329490
     maximum size of a front trapezoid       =         1761501
     no. of floating point ops for factor    =      7.8480D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9895
     ratio of allocated memory (max/min)     =          1.0810
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.061780
     time (cpu & wall) for matrix distrib.   =        0.078125        0.092104
     time (cpu & wall) for numeric factor    =        0.156250        0.236832
     computational rate (gflops) for factor  =       50.227043       33.137352

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        112000.        1. MB
                95-   1         65536.        0. MB         48965.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160965.        1. MB


  Solver Memory allocated on core    0       =      138.280 MB
  Solver Memory allocated on core    1       =      149.475 MB
  Total Solver Memory allocated by all cores =      287.755 MB





  Performance statistics for DSP solver: icalls =     22

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3449655
     no. of nonzeroes in the factor l        =         6843318
     ratio of nonzeroes in factor (min/max)  =          0.7272
     number of super nodes                   =             589
     maximum order of a front matrix         =            2580
     maximum size of a front matrix          =         3329490
     maximum size of a front trapezoid       =         1761501
     no. of floating point ops for factor    =      7.8480D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9895
     ratio of allocated memory (max/min)     =          1.0810
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.010768
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.058833
     time (cpu & wall) for matrix distrib.   =        0.093750        0.096564
     time (cpu & wall) for numeric factor    =        0.187500        0.214205
     computational rate (gflops) for factor  =       41.855869       36.637771

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        112000.        1. MB
                95-   1         65536.        0. MB         48965.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160965.        1. MB


  Solver Memory allocated on core    0       =      138.276 MB
  Solver Memory allocated on core    1       =      149.470 MB
  Total Solver Memory allocated by all cores =      287.746 MB





  Performance statistics for DSP solver: icalls =     23

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3448710
     no. of nonzeroes in the factor l        =         6730260
     ratio of nonzeroes in factor (min/max)  =          0.8206
     number of super nodes                   =             610
     maximum order of a front matrix         =            2535
     maximum size of a front matrix          =         3214380
     maximum size of a front trapezoid       =         1761501
     no. of floating point ops for factor    =      7.5746D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9734
     ratio of allocated memory (max/min)     =          1.2026
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.011468
     time (cpu & wall) for ordering          =        0.031250        0.087019
     time (cpu & wall) for other matrix prep =        0.015625        0.010462
     time (cpu & wall) for value input       =        0.046875        0.069175
     time (cpu & wall) for matrix distrib.   =        0.046875        0.092361
     time (cpu & wall) for numeric factor    =        0.109375        0.211044
     computational rate (gflops) for factor  =       69.253541       35.891071

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        102141.        1. MB
                95-   1         65536.        0. MB         60887.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        163028.        1. MB


  Solver Memory allocated on core    0       =      128.642 MB
  Solver Memory allocated on core    1       =      154.700 MB
  Total Solver Memory allocated by all cores =      283.342 MB





  Performance statistics for DSP solver: icalls =     24

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3448710
     no. of nonzeroes in the factor l        =         6606062
     ratio of nonzeroes in factor (min/max)  =          0.9182
     number of super nodes                   =             602
     maximum order of a front matrix         =            2577
     maximum size of a front matrix          =         3321753
     maximum size of a front trapezoid       =         1776939
     no. of floating point ops for factor    =      7.2506D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9952
     ratio of allocated memory (max/min)     =          1.2965
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.011364
     time (cpu & wall) for ordering          =        0.046875        0.081718
     time (cpu & wall) for other matrix prep =        0.000000        0.009612
     time (cpu & wall) for value input       =        0.031250        0.064271
     time (cpu & wall) for matrix distrib.   =        0.125000        0.097748
     time (cpu & wall) for numeric factor    =        0.203125        0.200025
     computational rate (gflops) for factor  =       35.695324       36.248587

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         55392.        0. MB
                95-   1        131072.        1. MB        105562.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160954.        1. MB


  Solver Memory allocated on core    0       =      121.845 MB
  Solver Memory allocated on core    1       =      157.978 MB
  Total Solver Memory allocated by all cores =      279.823 MB





  Performance statistics for DSP solver: icalls =     25

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3448710
     no. of nonzeroes in the factor l        =         6606062
     ratio of nonzeroes in factor (min/max)  =          0.9182
     number of super nodes                   =             602
     maximum order of a front matrix         =            2577
     maximum size of a front matrix          =         3321753
     maximum size of a front trapezoid       =         1776939
     no. of floating point ops for factor    =      7.2506D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9952
     ratio of allocated memory (max/min)     =          1.2965
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.010824
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.071611
     time (cpu & wall) for matrix distrib.   =        0.046875        0.103704
     time (cpu & wall) for numeric factor    =        0.140625        0.199094
     computational rate (gflops) for factor  =       51.559913       36.418074
     time (cpu & wall) for numeric solve     =        0.015625        0.006868
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         55392.        0. MB
                95-   1        131072.        1. MB        105562.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160954.        1. MB


  Solver Memory allocated on core    0       =      121.874 MB
  Solver Memory allocated on core    1       =      158.004 MB
  Total Solver Memory allocated by all cores =      279.878 MB





  Performance statistics for DSP solver: icalls =     26

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3447630
     no. of nonzeroes in the factor l        =         6890931
     ratio of nonzeroes in factor (min/max)  =          0.7069
     number of super nodes                   =             613
     maximum order of a front matrix         =            2613
     maximum size of a front matrix          =         3415191
     maximum size of a front trapezoid       =         1207170
     no. of floating point ops for factor    =      8.0516D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9843
     ratio of allocated memory (max/min)     =          1.0543
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.011219
     time (cpu & wall) for ordering          =        0.062500        0.088955
     time (cpu & wall) for other matrix prep =        0.015625        0.010483
     time (cpu & wall) for value input       =        0.078125        0.080493
     time (cpu & wall) for matrix distrib.   =        0.093750        0.099406
     time (cpu & wall) for numeric factor    =        0.156250        0.227685
     computational rate (gflops) for factor  =       51.530553       35.363168

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        116211.        1. MB
                95-   1         65536.        0. MB         47573.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        163784.        1. MB


  Solver Memory allocated on core    0       =      141.685 MB
  Solver Memory allocated on core    1       =      149.385 MB
  Total Solver Memory allocated by all cores =      291.070 MB





  Performance statistics for DSP solver: icalls =     27

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3568959
     no. of nonzeroes in the factor l        =         6863418
     ratio of nonzeroes in factor (min/max)  =          0.8992
     number of super nodes                   =             608
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1138D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9063
     ratio of allocated memory (max/min)     =          1.1616
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.012577
     time (cpu & wall) for ordering          =        0.078125        0.087157
     time (cpu & wall) for other matrix prep =        0.015625        0.012233
     time (cpu & wall) for value input       =        0.031250        0.067074
     time (cpu & wall) for matrix distrib.   =        0.093750        0.101040
     time (cpu & wall) for numeric factor    =        0.093750        0.204953
     computational rate (gflops) for factor  =       86.547105       39.588545

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         58249.        0. MB
                95-   1        131072.        1. MB        104151.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162400.        1. MB


  Solver Memory allocated on core    0       =      136.988 MB
  Solver Memory allocated on core    1       =      159.125 MB
  Total Solver Memory allocated by all cores =      296.114 MB





  Performance statistics for DSP solver: icalls =     28

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3568959
     no. of nonzeroes in the factor l        =         6863418
     ratio of nonzeroes in factor (min/max)  =          0.8992
     number of super nodes                   =             608
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1138D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9063
     ratio of allocated memory (max/min)     =          1.1617
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.063193
     time (cpu & wall) for matrix distrib.   =        0.093750        0.117171
     time (cpu & wall) for numeric factor    =        0.187500        0.203876
     computational rate (gflops) for factor  =       43.273553       39.797755

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         58249.        0. MB
                95-   1        131072.        1. MB        104151.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162400.        1. MB


  Solver Memory allocated on core    0       =      137.007 MB
  Solver Memory allocated on core    1       =      159.164 MB
  Total Solver Memory allocated by all cores =      296.171 MB





  Performance statistics for DSP solver: icalls =     29

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3568959
     no. of nonzeroes in the factor l        =         6863418
     ratio of nonzeroes in factor (min/max)  =          0.8992
     number of super nodes                   =             608
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1138D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9063
     ratio of allocated memory (max/min)     =          1.1617
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.067097
     time (cpu & wall) for matrix distrib.   =        0.078125        0.100298
     time (cpu & wall) for numeric factor    =        0.203125        0.228965
     computational rate (gflops) for factor  =       39.944818       35.436803

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         58249.        0. MB
                95-   1        131072.        1. MB        104151.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162400.        1. MB


  Solver Memory allocated on core    0       =      137.007 MB
  Solver Memory allocated on core    1       =      159.164 MB
  Total Solver Memory allocated by all cores =      296.171 MB





  Performance statistics for DSP solver: icalls =     30

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3568959
     no. of nonzeroes in the factor l        =         6863418
     ratio of nonzeroes in factor (min/max)  =          0.8992
     number of super nodes                   =             608
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1138D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9063
     ratio of allocated memory (max/min)     =          1.1617
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.012786
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.062500        0.061222
     time (cpu & wall) for matrix distrib.   =        0.062500        0.098559
     time (cpu & wall) for numeric factor    =        0.187500        0.200603
     computational rate (gflops) for factor  =       43.273553       40.447048

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         58249.        0. MB
                95-   1        131072.        1. MB        104151.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162400.        1. MB


  Solver Memory allocated on core    0       =      136.999 MB
  Solver Memory allocated on core    1       =      159.152 MB
  Total Solver Memory allocated by all cores =      296.151 MB





  Performance statistics for DSP solver: icalls =     31

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3446550
     no. of nonzeroes in the factor l        =         6898091
     ratio of nonzeroes in factor (min/max)  =          0.7628
     number of super nodes                   =             610
     maximum order of a front matrix         =            2523
     maximum size of a front matrix          =         3184026
     maximum size of a front trapezoid       =         1882596
     no. of floating point ops for factor    =      8.1770D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9380
     ratio of allocated memory (max/min)     =          1.0972
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.011274
     time (cpu & wall) for ordering          =        0.078125        0.081756
     time (cpu & wall) for other matrix prep =        0.000000        0.009900
     time (cpu & wall) for value input       =        0.031250        0.056547
     time (cpu & wall) for matrix distrib.   =        0.125000        0.109396
     time (cpu & wall) for numeric factor    =        0.140625        0.243772
     computational rate (gflops) for factor  =       58.147512       33.543545

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107657.        1. MB
                95-   1         65536.        0. MB         56677.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        164334.        1. MB


  Solver Memory allocated on core    0       =      136.366 MB
  Solver Memory allocated on core    1       =      149.614 MB
  Total Solver Memory allocated by all cores =      285.980 MB





  Performance statistics for DSP solver: icalls =     32

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3446550
     no. of nonzeroes in the factor l        =         6594557
     ratio of nonzeroes in factor (min/max)  =          0.9728
     number of super nodes                   =             611
     maximum order of a front matrix         =            2514
     maximum size of a front matrix          =         3161355
     maximum size of a front trapezoid       =         1562130
     no. of floating point ops for factor    =      7.2567D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8567
     ratio of allocated memory (max/min)     =          1.1196
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.011097
     time (cpu & wall) for ordering          =        0.062500        0.083395
     time (cpu & wall) for other matrix prep =        0.015625        0.009803
     time (cpu & wall) for value input       =        0.031250        0.062260
     time (cpu & wall) for matrix distrib.   =        0.046875        0.103520
     time (cpu & wall) for numeric factor    =        0.171875        0.176356
     computational rate (gflops) for factor  =       42.220878       41.148188

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         58244.        0. MB
                95-   1        131072.        1. MB        103770.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162014.        1. MB


  Solver Memory allocated on core    0       =      135.425 MB
  Solver Memory allocated on core    1       =      151.626 MB
  Total Solver Memory allocated by all cores =      287.051 MB





  Performance statistics for DSP solver: icalls =     33

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1364
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.012919
     time (cpu & wall) for ordering          =        0.062500        0.083781
     time (cpu & wall) for other matrix prep =        0.000000        0.010757
     time (cpu & wall) for value input       =        0.015625        0.057608
     time (cpu & wall) for matrix distrib.   =        0.093750        0.095438
     time (cpu & wall) for numeric factor    =        0.171875        0.200032
     computational rate (gflops) for factor  =       47.203873       40.559400

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.496 MB
  Solver Memory allocated on core    1       =      157.388 MB
  Total Solver Memory allocated by all cores =      295.884 MB





  Performance statistics for DSP solver: icalls =     34

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1363
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.058693
     time (cpu & wall) for matrix distrib.   =        0.062500        0.096360
     time (cpu & wall) for numeric factor    =        0.140625        0.197470
     computational rate (gflops) for factor  =       57.693623       41.085561
     time (cpu & wall) for numeric solve     =        0.015625        0.006283
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.539 MB
  Solver Memory allocated on core    1       =      157.427 MB
  Total Solver Memory allocated by all cores =      295.966 MB





  Performance statistics for DSP solver: icalls =     35

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1363
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.068244
     time (cpu & wall) for matrix distrib.   =        0.062500        0.095512
     time (cpu & wall) for numeric factor    =        0.156250        0.208663
     computational rate (gflops) for factor  =       51.924260       38.881688
     time (cpu & wall) for numeric solve     =        0.015625        0.006312
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.539 MB
  Solver Memory allocated on core    1       =      157.427 MB
  Total Solver Memory allocated by all cores =      295.966 MB





  Performance statistics for DSP solver: icalls =     36

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1363
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.078125        0.071352
     time (cpu & wall) for matrix distrib.   =        0.031250        0.104450
     time (cpu & wall) for numeric factor    =        0.156250        0.209750
     computational rate (gflops) for factor  =       51.924260       38.680133
     time (cpu & wall) for numeric solve     =        0.015625        0.006568
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.539 MB
  Solver Memory allocated on core    1       =      157.427 MB
  Total Solver Memory allocated by all cores =      295.966 MB





  Performance statistics for DSP solver: icalls =     37

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1363
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.062500        0.078969
     time (cpu & wall) for matrix distrib.   =        0.062500        0.095136
     time (cpu & wall) for numeric factor    =        0.171875        0.214745
     computational rate (gflops) for factor  =       47.203873       37.780499

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.539 MB
  Solver Memory allocated on core    1       =      157.427 MB
  Total Solver Memory allocated by all cores =      295.966 MB





  Performance statistics for DSP solver: icalls =     38

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1363
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.063189
     time (cpu & wall) for matrix distrib.   =        0.078125        0.104730
     time (cpu & wall) for numeric factor    =        0.140625        0.208121
     computational rate (gflops) for factor  =       57.693623       38.982964

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.539 MB
  Solver Memory allocated on core    1       =      157.427 MB
  Total Solver Memory allocated by all cores =      295.966 MB





  Performance statistics for DSP solver: icalls =     39

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1363
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.061647
     time (cpu & wall) for matrix distrib.   =        0.125000        0.115765
     time (cpu & wall) for numeric factor    =        0.156250        0.241011
     computational rate (gflops) for factor  =       51.924260       33.663037

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.539 MB
  Solver Memory allocated on core    1       =      157.427 MB
  Total Solver Memory allocated by all cores =      295.966 MB





  Performance statistics for DSP solver: icalls =     40

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3446550
     no. of nonzeroes in the factor l        =         7022790
     ratio of nonzeroes in factor (min/max)  =          0.7979
     number of super nodes                   =             611
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2872125
     no. of floating point ops for factor    =      8.5472D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9572
     ratio of allocated memory (max/min)     =          1.1598
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.010905
     time (cpu & wall) for ordering          =        0.031250        0.079506
     time (cpu & wall) for other matrix prep =        0.000000        0.012286
     time (cpu & wall) for value input       =        0.015625        0.066250
     time (cpu & wall) for matrix distrib.   =        0.062500        0.101627
     time (cpu & wall) for numeric factor    =        0.109375        0.205654
     computational rate (gflops) for factor  =       78.146211       41.561252

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        114333.        1. MB
                95-   1         65536.        0. MB         48168.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162501.        1. MB


  Solver Memory allocated on core    0       =      135.798 MB
  Solver Memory allocated on core    1       =      157.495 MB
  Total Solver Memory allocated by all cores =      293.293 MB





  Performance statistics for DSP solver: icalls =     41

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1364
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.011983
     time (cpu & wall) for ordering          =        0.046875        0.083417
     time (cpu & wall) for other matrix prep =        0.000000        0.009623
     time (cpu & wall) for value input       =        0.046875        0.058206
     time (cpu & wall) for matrix distrib.   =        0.062500        0.096770
     time (cpu & wall) for numeric factor    =        0.218750        0.260003
     computational rate (gflops) for factor  =       37.088757       31.204171

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.496 MB
  Solver Memory allocated on core    1       =      157.388 MB
  Total Solver Memory allocated by all cores =      295.884 MB





  Performance statistics for DSP solver: icalls =     42

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1363
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.062457
     time (cpu & wall) for matrix distrib.   =        0.062500        0.097079
     time (cpu & wall) for numeric factor    =        0.265625        0.262041
     computational rate (gflops) for factor  =       30.543683       30.961472

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.539 MB
  Solver Memory allocated on core    1       =      157.427 MB
  Total Solver Memory allocated by all cores =      295.966 MB





  Performance statistics for DSP solver: icalls =     43

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1363
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.065002
     time (cpu & wall) for matrix distrib.   =        0.109375        0.098726
     time (cpu & wall) for numeric factor    =        0.125000        0.226563
     computational rate (gflops) for factor  =       64.905326       35.809772

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.539 MB
  Solver Memory allocated on core    1       =      157.427 MB
  Total Solver Memory allocated by all cores =      295.966 MB





  Performance statistics for DSP solver: icalls =     44

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1363
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.059719
     time (cpu & wall) for matrix distrib.   =        0.093750        0.111360
     time (cpu & wall) for numeric factor    =        0.156250        0.230479
     computational rate (gflops) for factor  =       51.924260       35.201369

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.539 MB
  Solver Memory allocated on core    1       =      157.427 MB
  Total Solver Memory allocated by all cores =      295.966 MB





  Performance statistics for DSP solver: icalls =     45

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1363
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.062500        0.066829
     time (cpu & wall) for matrix distrib.   =        0.125000        0.123232
     time (cpu & wall) for numeric factor    =        0.140625        0.222654
     computational rate (gflops) for factor  =       57.693623       36.438446
     time (cpu & wall) for numeric solve     =        0.015625        0.006755
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.539 MB
  Solver Memory allocated on core    1       =      157.427 MB
  Total Solver Memory allocated by all cores =      295.966 MB





  Performance statistics for DSP solver: icalls =     46

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1363
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.060975
     time (cpu & wall) for matrix distrib.   =        0.109375        0.107241
     time (cpu & wall) for numeric factor    =        0.218750        0.225846
     computational rate (gflops) for factor  =       37.088757       35.923506

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.539 MB
  Solver Memory allocated on core    1       =      157.427 MB
  Total Solver Memory allocated by all cores =      295.966 MB





  Performance statistics for DSP solver: icalls =     47

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1363
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.060918
     time (cpu & wall) for matrix distrib.   =        0.078125        0.100101
     time (cpu & wall) for numeric factor    =        0.187500        0.222348
     computational rate (gflops) for factor  =       43.270217       36.488544
     time (cpu & wall) for numeric solve     =        0.015625        0.006456
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.539 MB
  Solver Memory allocated on core    1       =      157.427 MB
  Total Solver Memory allocated by all cores =      295.966 MB





  Performance statistics for DSP solver: icalls =     48

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3567879
     no. of nonzeroes in the factor l        =         6851204
     ratio of nonzeroes in factor (min/max)  =          0.9455
     number of super nodes                   =             615
     maximum order of a front matrix         =            2694
     maximum size of a front matrix          =         3630165
     maximum size of a front trapezoid       =         2168925
     no. of floating point ops for factor    =      8.1132D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.8880
     ratio of allocated memory (max/min)     =          1.1363
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.057229
     time (cpu & wall) for matrix distrib.   =        0.078125        0.112692
     time (cpu & wall) for numeric factor    =        0.171875        0.209465
     computational rate (gflops) for factor  =       47.203873       38.732780

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         65536.        0. MB         57801.        0. MB
                95-   1        131072.        1. MB        104749.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162550.        1. MB


  Solver Memory allocated on core    0       =      138.539 MB
  Solver Memory allocated on core    1       =      157.427 MB
  Total Solver Memory allocated by all cores =      295.966 MB





  Performance statistics for DSP solver: icalls =     49

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0119
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.028926
     time (cpu & wall) for ordering          =        0.046875        0.085523
     time (cpu & wall) for other matrix prep =        0.000000        0.009414
     time (cpu & wall) for value input       =        0.078125        0.130192
     time (cpu & wall) for matrix distrib.   =        0.156250        0.201879
     time (cpu & wall) for numeric factor    =        0.187500        0.228091
     computational rate (gflops) for factor  =       43.780306       35.989193

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.433 MB
  Solver Memory allocated on core    1       =      145.702 MB
  Total Solver Memory allocated by all cores =      293.135 MB





  Performance statistics for DSP solver: icalls =     50

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.016192
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.064669
     time (cpu & wall) for matrix distrib.   =        0.046875        0.114932
     time (cpu & wall) for numeric factor    =        0.156250        0.214495
     computational rate (gflops) for factor  =       52.536367       38.270426

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.510 MB
  Solver Memory allocated on core    1       =      145.717 MB
  Total Solver Memory allocated by all cores =      293.228 MB





  Performance statistics for DSP solver: icalls =     51

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.011929
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.063516
     time (cpu & wall) for matrix distrib.   =        0.093750        0.098894
     time (cpu & wall) for numeric factor    =        0.250000        0.251851
     computational rate (gflops) for factor  =       32.835229       32.593917

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.506 MB
  Solver Memory allocated on core    1       =      145.713 MB
  Total Solver Memory allocated by all cores =      293.220 MB





  Performance statistics for DSP solver: icalls =     52

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.011885
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.060568
     time (cpu & wall) for matrix distrib.   =        0.093750        0.104775
     time (cpu & wall) for numeric factor    =        0.187500        0.256435
     computational rate (gflops) for factor  =       43.780306       32.011310

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.508 MB
  Solver Memory allocated on core    1       =      145.714 MB
  Total Solver Memory allocated by all cores =      293.223 MB





  Performance statistics for DSP solver: icalls =     53

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.063336
     time (cpu & wall) for matrix distrib.   =        0.093750        0.099227
     time (cpu & wall) for numeric factor    =        0.171875        0.216569
     computational rate (gflops) for factor  =       47.760334       37.903802
     time (cpu & wall) for numeric solve     =        0.015625        0.006780
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.508 MB
  Solver Memory allocated on core    1       =      145.714 MB
  Total Solver Memory allocated by all cores =      293.223 MB





  Performance statistics for DSP solver: icalls =     54

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.016476
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.063829
     time (cpu & wall) for matrix distrib.   =        0.078125        0.107169
     time (cpu & wall) for numeric factor    =        0.234375        0.247481
     computational rate (gflops) for factor  =       35.024245       33.169498

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.510 MB
  Solver Memory allocated on core    1       =      145.717 MB
  Total Solver Memory allocated by all cores =      293.228 MB





  Performance statistics for DSP solver: icalls =     55

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.072501
     time (cpu & wall) for matrix distrib.   =        0.093750        0.119376
     time (cpu & wall) for numeric factor    =        0.265625        0.249386
     computational rate (gflops) for factor  =       30.903745       32.916058

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.510 MB
  Solver Memory allocated on core    1       =      145.717 MB
  Total Solver Memory allocated by all cores =      293.228 MB





  Performance statistics for DSP solver: icalls =     56

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.012723
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.062500        0.057318
     time (cpu & wall) for matrix distrib.   =        0.000000        0.100366
     time (cpu & wall) for numeric factor    =        0.156250        0.213633
     computational rate (gflops) for factor  =       52.536367       38.424846
     time (cpu & wall) for numeric solve     =        0.015625        0.006578
     computational rate (gflops) for solve   =        0.000000        0.000000
     effective I/O rate (GB/sec) for solve   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.510 MB
  Solver Memory allocated on core    1       =      145.717 MB
  Total Solver Memory allocated by all cores =      293.228 MB





  Performance statistics for DSP solver: icalls =     57

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.012052
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.059279
     time (cpu & wall) for matrix distrib.   =        0.078125        0.102005
     time (cpu & wall) for numeric factor    =        0.187500        0.235664
     computational rate (gflops) for factor  =       43.780306       34.832689

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.519 MB
  Solver Memory allocated on core    1       =      145.730 MB
  Total Solver Memory allocated by all cores =      293.248 MB





  Performance statistics for DSP solver: icalls =     58

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.012819
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.059214
     time (cpu & wall) for matrix distrib.   =        0.078125        0.102650
     time (cpu & wall) for numeric factor    =        0.156250        0.225036
     computational rate (gflops) for factor  =       52.536367       36.477817

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.512 MB
  Solver Memory allocated on core    1       =      145.721 MB
  Total Solver Memory allocated by all cores =      293.233 MB





  Performance statistics for DSP solver: icalls =     59

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.060648
     time (cpu & wall) for matrix distrib.   =        0.093750        0.109049
     time (cpu & wall) for numeric factor    =        0.171875        0.235375
     computational rate (gflops) for factor  =       47.760334       34.875384

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.512 MB
  Solver Memory allocated on core    1       =      145.721 MB
  Total Solver Memory allocated by all cores =      293.233 MB





  Performance statistics for DSP solver: icalls =     60

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.062629
     time (cpu & wall) for matrix distrib.   =        0.046875        0.115418
     time (cpu & wall) for numeric factor    =        0.156250        0.209526
     computational rate (gflops) for factor  =       52.536367       39.178027

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.512 MB
  Solver Memory allocated on core    1       =      145.721 MB
  Total Solver Memory allocated by all cores =      293.233 MB





  Performance statistics for DSP solver: icalls =     61

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.062155
     time (cpu & wall) for matrix distrib.   =        0.109375        0.115247
     time (cpu & wall) for numeric factor    =        0.171875        0.201827
     computational rate (gflops) for factor  =       47.760334       40.672413

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.512 MB
  Solver Memory allocated on core    1       =      145.721 MB
  Total Solver Memory allocated by all cores =      293.233 MB





  Performance statistics for DSP solver: icalls =     62

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.069337
     time (cpu & wall) for matrix distrib.   =        0.046875        0.112790
     time (cpu & wall) for numeric factor    =        0.125000        0.216281
     computational rate (gflops) for factor  =       65.670459       37.954432

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.512 MB
  Solver Memory allocated on core    1       =      145.721 MB
  Total Solver Memory allocated by all cores =      293.233 MB





  Performance statistics for DSP solver: icalls =     63

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.059483
     time (cpu & wall) for matrix distrib.   =        0.031250        0.107304
     time (cpu & wall) for numeric factor    =        0.109375        0.217764
     computational rate (gflops) for factor  =       75.051953       37.695836

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.512 MB
  Solver Memory allocated on core    1       =      145.721 MB
  Total Solver Memory allocated by all cores =      293.233 MB





  Performance statistics for DSP solver: icalls =     64

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.066287
     time (cpu & wall) for matrix distrib.   =        0.093750        0.099688
     time (cpu & wall) for numeric factor    =        0.140625        0.201057
     computational rate (gflops) for factor  =       58.373741       40.828341

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.512 MB
  Solver Memory allocated on core    1       =      145.721 MB
  Total Solver Memory allocated by all cores =      293.233 MB





  Performance statistics for DSP solver: icalls =     65

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3570039
     no. of nonzeroes in the factor l        =         6887562
     ratio of nonzeroes in factor (min/max)  =          0.6957
     number of super nodes                   =             603
     maximum order of a front matrix         =            2721
     maximum size of a front matrix          =         3703281
     maximum size of a front trapezoid       =         2036121
     no. of floating point ops for factor    =      8.2088D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9296
     ratio of allocated memory (max/min)     =          1.0123
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.012474
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.060650
     time (cpu & wall) for matrix distrib.   =        0.078125        0.099967
     time (cpu & wall) for numeric factor    =        0.203125        0.242924
     computational rate (gflops) for factor  =       40.412590       33.791669

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        107904.        1. MB
                95-   1         65536.        0. MB         52932.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        160836.        1. MB


  Solver Memory allocated on core    0       =      147.508 MB
  Solver Memory allocated on core    1       =      145.716 MB
  Total Solver Memory allocated by all cores =      293.225 MB





  Performance statistics for DSP solver: icalls =     66

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3571839
     no. of nonzeroes in the factor l        =         7069811
     ratio of nonzeroes in factor (min/max)  =          0.7893
     number of super nodes                   =             612
     maximum order of a front matrix         =            2688
     maximum size of a front matrix          =         3614016
     maximum size of a front trapezoid       =         2217021
     no. of floating point ops for factor    =      8.5114D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9594
     ratio of allocated memory (max/min)     =          1.0972
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.025290
     time (cpu & wall) for ordering          =        0.031250        0.081268
     time (cpu & wall) for other matrix prep =        0.000000        0.009178
     time (cpu & wall) for value input       =        0.031250        0.117067
     time (cpu & wall) for matrix distrib.   =        0.156250        0.199688
     time (cpu & wall) for numeric factor    =        0.156250        0.225377
     computational rate (gflops) for factor  =       54.472712       37.765012

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        104372.        1. MB
                95-   1         65536.        0. MB         57845.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162217.        1. MB


  Solver Memory allocated on core    0       =      141.345 MB
  Solver Memory allocated on core    1       =      155.090 MB
  Total Solver Memory allocated by all cores =      296.435 MB





  Performance statistics for DSP solver: icalls =     67

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3571839
     no. of nonzeroes in the factor l        =         7069811
     ratio of nonzeroes in factor (min/max)  =          0.7893
     number of super nodes                   =             612
     maximum order of a front matrix         =            2688
     maximum size of a front matrix          =         3614016
     maximum size of a front trapezoid       =         2217021
     no. of floating point ops for factor    =      8.5114D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9594
     ratio of allocated memory (max/min)     =          1.0972
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.014816
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.062500        0.061230
     time (cpu & wall) for matrix distrib.   =        0.109375        0.100254
     time (cpu & wall) for numeric factor    =        0.171875        0.214479
     computational rate (gflops) for factor  =       49.520647       39.683799

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        104372.        1. MB
                95-   1         65536.        0. MB         57845.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162217.        1. MB


  Solver Memory allocated on core    0       =      141.410 MB
  Solver Memory allocated on core    1       =      155.157 MB
  Total Solver Memory allocated by all cores =      296.567 MB





  Performance statistics for DSP solver: icalls =     68

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3571839
     no. of nonzeroes in the factor l        =         7069811
     ratio of nonzeroes in factor (min/max)  =          0.7893
     number of super nodes                   =             612
     maximum order of a front matrix         =            2688
     maximum size of a front matrix          =         3614016
     maximum size of a front trapezoid       =         2217021
     no. of floating point ops for factor    =      8.5114D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9594
     ratio of allocated memory (max/min)     =          1.0972
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.011734
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.061554
     time (cpu & wall) for matrix distrib.   =        0.046875        0.093969
     time (cpu & wall) for numeric factor    =        0.156250        0.220210
     computational rate (gflops) for factor  =       54.472712       38.651112

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        104372.        1. MB
                95-   1         65536.        0. MB         57845.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162217.        1. MB


  Solver Memory allocated on core    0       =      141.402 MB
  Solver Memory allocated on core    1       =      155.153 MB
  Total Solver Memory allocated by all cores =      296.554 MB





  Performance statistics for DSP solver: icalls =     69

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3571839
     no. of nonzeroes in the factor l        =         7069811
     ratio of nonzeroes in factor (min/max)  =          0.7893
     number of super nodes                   =             612
     maximum order of a front matrix         =            2688
     maximum size of a front matrix          =         3614016
     maximum size of a front trapezoid       =         2217021
     no. of floating point ops for factor    =      8.5114D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9594
     ratio of allocated memory (max/min)     =          1.0972
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.011825
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.057445
     time (cpu & wall) for matrix distrib.   =        0.062500        0.105529
     time (cpu & wall) for numeric factor    =        0.187500        0.219623
     computational rate (gflops) for factor  =       45.393927       38.754434

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        104372.        1. MB
                95-   1         65536.        0. MB         57845.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162217.        1. MB


  Solver Memory allocated on core    0       =      141.402 MB
  Solver Memory allocated on core    1       =      155.149 MB
  Total Solver Memory allocated by all cores =      296.551 MB





  Performance statistics for DSP solver: icalls =     70

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           18054
     no. of nonzeroes in lower triangle of a =         3571839
     no. of nonzeroes in the factor l        =         7069811
     ratio of nonzeroes in factor (min/max)  =          0.7893
     number of super nodes                   =             612
     maximum order of a front matrix         =            2688
     maximum size of a front matrix          =         3614016
     maximum size of a front trapezoid       =         2217021
     no. of floating point ops for factor    =      8.5114D+09
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          0.9594
     ratio of allocated memory (max/min)     =          1.0972
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               6
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.059017
     time (cpu & wall) for matrix distrib.   =        0.046875        0.092685
     time (cpu & wall) for numeric factor    =        0.140625        0.216241
     computational rate (gflops) for factor  =       60.525236       39.360589

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        131072.        1. MB        104372.        1. MB
                95-   1         65536.        0. MB         57845.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:        196608.        2. MB        162217.        1. MB


  Solver Memory allocated on core    0       =      141.402 MB
  Solver Memory allocated on core    1       =      155.149 MB
  Total Solver Memory allocated by all cores =      296.551 MB

